@extends('cms.cms_master')
@section('main_content')
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
<h3>Edit Product</h3>
</div>

<div class="row">
  <div class="col-8">
  <form action="{{ url('cms/products/' . $product_item['id']) }}" method="POST" novalidate="novalidate" autocomplete="off" enctype="multipart/form-data">
    @method('PUT')
    @csrf
    <input type="hidden" name="item_id" value=" {{$product_item['id']}} ">
    <div class="form-group">
        <label for="category-id"><span class="text-danger">*</span> Select Product Category:</label>
        <select name="category_id" id="category-id" class="form-control" >
          @foreach($categories as $category)
          <option @if($product_item['categorie_id'] == $category['id']) selected="selected" @endif value="{{$category['id']}}">{{$category['ctitle']}}</option>
          @endforeach
        </select>
        <span class="text-danger">{{$errors->first('category_id')}}</span>
    </div> 

    <div class="form-group">
        <label for="title"><span class="text-danger">*</span> Title:</label>
        <input value="{{ $product_item['ptitle'] }}" type="text" name="ptitle" id="title" class="form-control field-input-cms original-text">
        <small class="text-muted">Title is start with uppercase (ex. The Title)</small>
        <br><span class="text-danger">{{$errors->first('ptitle')}}</span>
    </div> 

    <div class="form-group">
        <label for="url"><span class="text-danger">*</span> Product URL: <small class="text-muted">  (Auto generated by your Link)</small> </label>
        <input value="{{ $product_item['purl'] }}" type="text" name="purl" id="url" class="form-control field-input-cms target-text">
        <small class="text-muted">Only lowercase a-z and 0-9 (ex. classic-bath)</small>
        <br><span class="text-danger">{{$errors->first('purl')}}</span>
    </div> 

    <div class="form-group">
        <label for="price"><span class="text-danger">*</span> Price: </label>
        <input value="{{ $product_item['price'] }}" type="text" name="price" id="price" class="form-control field-input-cms">
        <small class="text-muted">Only numbers (ex. $770.00 or $28)</small>
        <br><span class="text-danger">{{$errors->first('price')}}</span>
    </div> 

    <div class="form-group">
        <label for="article"><span class="text-danger">*</span> Description </label>
        <textarea name="particle" id="article" class="form-control">{{ $product_item['particle'] }}</textarea>
        <small class="text-muted">The description is mins 20 characters</small>
        <br><span class="text-danger">{{$errors->first('particle')}}</span>
    </div> 

    <div class="form-group">
        <label for="image"><span class="text-danger">*</span> Product Image </label>
        <br><span><img src="{{ asset('images/' . $product_item['pimage']) }}" height="80" width="100" alt=""></span>
        <div class="input-group mt-2 mb-3">
  <div class="input-group-prepend">
    <span class="input-group-text">Upload</span>
  </div>
  <div class="custom-file">
    <input name="image" type="file" class="custom-file-input" id="inputGroupFile01">
    <label class="custom-file-label" for="inputGroupFile01">Choose Product Image</label>
  </div>
  </div>
      <div class="form-group">
      <small class="text-muted">Type: JPG, JPEG, PNG, GIF | Max size: 5mb</small>
      <br><span class="text-danger">{{$errors->first('pimage')}}</span>
      </div>
      <input class="btn btn-primary" type="submit" name="submit" value="Save Product">
      <a class="btn btn-secondary " href="{{url('cms/products')}}"> Cancel </a>
    </form>
  </div>
</div>
@endsection

